### ISSUE TITLE
ModuleNotFoundError: No module named 'imageio'

### ISSUE THREAD

**Issue by Awais9** [bentoml/gallery#12]
Hello there!
I am trying to run the **Fast AI Pet Image classification** example but I'm facing the following issue 
<img width="985" alt="Screenshot 2020-01-16 at 5 20 29 PM" src="https://user-images.githubusercontent.com/37929195/72524851-9a130e00-3884-11ea-9f0b-4d78fac09701.png">
Please check it and let me know the solution for it to run. Thanks in advance.

**Comment by parano** [comment]
Hi @Awais9, you will need to run `pip install imageio` to install `imageio`, which is an optional dependency, only required when you use ImageHandler or FastaiImageHandler

**Comment by Awais9** [comment]
I have tried pack with multiple possibilities to pack the model and following are the screenshots. 
1) Tried with **service.pack(pet_classifer=learnModel)** which is posted with example and get following error
<img width="1392" alt="Screenshot 2020-01-17 at 12 09 52 PM" src="https://user-images.githubusercontent.com/37929195/72598958-ab1a5880-3932-11ea-8453-b256cf95ed59.png">
2) Tried with **service.pack('pet_classifer',learnModel)** and get following error
<img width="1392" alt="Screenshot 2020-01-17 at 12 42 37 PM" src="https://user-images.githubusercontent.com/37929195/72599019-c4230980-3932-11ea-9e8a-406edbace587.png">
3) Tried with **service.pack('model',learnModel)** as it was asking for model in previous attempt and get the following error
<img width="1392" alt="Screenshot 2020-01-17 at 2 02 22 PM" src="https://user-images.githubusercontent.com/37929195/72599124-f03e8a80-3932-11ea-8dad-a8badd19471f.png">

Please let me know how to fix them and what is the correct way to pack the model. Thanks

**Comment by parano** [comment]
Hi @Awais9,

In terms of BentoML syntax, the code in the first screenshot was not correct, it should be:
`service.pack('pet_classifer',learnModel)` or `ServiceClass.pack(pet_classifier=learnModel)`, screenshot 2 and 3 are correct syntax.

The first parameter of `service.pack` is the "name" you gave to the artifact, I assume when you defined the BentoService class, you named the artifact by `@artifacts([FastaiModelArtifact("pet_classifer")])`, thus you should use`service.pack('pet_classifier',learnModel)` for packaging trained model. But if you had  `@artifacts([FastaiModelArtifact("model")])` instead, then you can use `service.pack('model',learnModel)`. Which is why you were seeing the error in screenshot 3.

The reason you see an error in screenshot 2, was because FastaiModelArtifact expect to pack an instance of fastai's `Learner` class or subclass. Could you tell me a bit more about your `GetLearnModel` function and what's the returned value?

**Comment by Awais9** [comment]
I guess the example is not updated yet as you mentioned because the first syntax is from it.
Yes! I am using **@artifacts([FastaiModelArtifact('pet_classifer')])** in service.
The **GetLearnModel** is defined class in setup.py to get the model as python was not importing the model instance directly so I made a class with function which just return the learn_model to BentoService.
I get the hints from your answers and will check my defined class as well. Thanks for update :)

**Comment by Awais9** [comment]
I put the learnModel directly instead to get from function and it works now. Thanks for the help :)
